# Generated by Django 2.2.3 on 2019-07-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='cQrCode',
        ),
        migrations.RenameField(
            model_name='cqrcode',
            old_name='hotel_Main_Img',
            new_name='QrCodeImg_name',
        ),
        migrations.RenameField(
            model_name='cqrcode',
            old_name='name',
            new_name='uniqueId',
        ),
    ]
