# Generated by Django 2.2.3 on 2019-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190720_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqrcode',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
