# Generated by Django 2.2.3 on 2019-07-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cqrcode_isauthenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqrcode',
            name='uniqueId',
            field=models.IntegerField(default=0),
        ),
    ]
